travis:
  secure:
    BINSTAR_TOKEN: S/IxpaOPflrnhDAfLj9gMByzxKL0HatyaUthHLBoPkWvuHP9nnT88aagOZmPmOwqUkBgQ88TV+5Or8+WEMYG80SUYJHxiGUKpGKs9oGkanIrDpLtkfDGUf25yIzGLiBD86pwUw24au752FKHBKymSoJ9GciyV0LcUYhPV0KnGWRRp4niKyG0nSowf+xuja337Tz/gh+aLGsquAmU7r0qWzTloET8/OAvM827rlbV4A5dGSElwI3lHRj0nWf7wRXbQkcyfRH4QtRB9x0wVIEIedmXjLZOu6n7yJRQSuMD6mRO7Pba2nxuNsTFQhLQ0VQfBUw9KoLDOI3Fu1yVT6Vh8qURVQz4+/q7cTfv4VczXgiPDDPEI57c2DavA+33HoN3uenZvI/jLxFbtwt3oxVhr951tkosKVzh5TFuE1E5GRoPza9UDKPq0fRNLaWXlZCO4RCtj9CrMSClqtVAKtuH7CjBP9MNm//Vh+o0H77oGe58wPHkZVu19fxPvSp5SUKvMVL3NS/zuWJk6vGoWfib3NIhjdD60pYdcMoubSeqQwX2v59AUzYSWBnt7ezKXlf4US/M+TsaZXu/B3PlhvdR0rHQdVDeHa0N7SBpYtrFjayqy40Nz/ytg9/5VVnJH8qBRYWkHGuimvHje+lPqsn0PmuXfXikW78b9LfafNUrdaA=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
conda_forge_output_validation: true
